const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const executablePath = 'C:/Users/hp/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe';
const baseURL = 'http://127.0.0.1:4173/';
const outputDir = path.join(process.cwd(), 'evidence', 'screenshots');
fs.mkdirSync(outputDir, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath, headless: true });
  const checks = [];
  const check = (name, value, details = '') => { checks.push({ name, pass: Boolean(value), details }); if (!value) throw new Error(`${name}: ${details}`); };
  const desktop = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
  await desktop.goto(baseURL, { waitUntil: 'domcontentloaded' });
  check('desktop title', await desktop.title() === 'VOTRA | Private commitment. Fair chance.');
  check('desktop no horizontal overflow', await desktop.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await desktop.screenshot({ path: path.join(outputDir, 'desktop-landing.png') });
  await desktop.locator('#setGoal').click(); await desktop.locator('#deposit').click();
  await desktop.locator('#how').scrollIntoViewIfNeeded();
  await desktop.screenshot({ path: path.join(outputDir, '01-goal-set.png'), clip: { x: 0, y: 0, width: 600, height: 400 } });
  await desktop.locator('#breach').click(); check('breach pauses weight', (await desktop.locator('#statusText').textContent()).includes('paused'));
  await desktop.screenshot({ path: path.join(outputDir, '03-breach-state.png'), clip: { x: 0, y: 0, width: 600, height: 400 } });
  await desktop.locator('#recover').click(); check('recovery resumes compliance', (await desktop.locator('#statusText').textContent()).includes('accumulating'));
  await desktop.screenshot({ path: path.join(outputDir, '02-compliant-state.png'), clip: { x: 0, y: 0, width: 600, height: 400 } });
  await desktop.locator('#proof').scrollIntoViewIfNeeded();
  await desktop.screenshot({ path: path.join(outputDir, '04-proof-receipt.png'), clip: { x: 0, y: 0, width: 600, height: 400 } });
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
  await mobile.goto(baseURL, { waitUntil: 'domcontentloaded' });
  check('mobile no horizontal overflow', await mobile.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  check('mobile hero visible', await mobile.locator('h1').isVisible());
  await mobile.screenshot({ path: path.join(outputDir, 'mobile-landing.png') });
  const proof = await browser.newPage({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 1 });
  await proof.goto(`${baseURL}proof/`, { waitUntil: 'domcontentloaded' });
  check('proof route title', await proof.title() === 'VOTRA Proof Record');
  check('proof evidence links', await proof.locator('a[href*="evidence/"]').count() >= 8);
  const report = { generatedAt: new Date().toISOString(), executablePath, baseURL, screenshots: fs.readdirSync(outputDir).sort(), checks };
  fs.writeFileSync(path.join(outputDir, 'report.json'), JSON.stringify(report, null, 2));
  await browser.close(); console.log(JSON.stringify(report, null, 2));
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
